#Name of entire workflow
name: Shell Commands

#After name we define events which will trigger the workflow

on: [push] # it can be array of events

#Git hosted runner
jobs: 
    run-shell-commad:
      runs-on: ubuntu-latest
      # steps would be array of object and each object defines a single step
      steps:
        - name: echo a string
          run: echo "Testing an echo command"
        - name: multiline script
          run: |
            node -v
            npm -v
        - name: python Command
          run: |
            import platform
            print(platform.processor())
          # This step lets user choose specific shell to run commands
          shell: python
    run-windows-command:
      runs-on: windows-latest
      steps:
        - name: Directory in powershell
          run: Get-Location
        - name: Directory in bach
          run: pwd
          # it will throw error if bash not specified
          shell: bash

